version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-cicd-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fv9ot1669nzf"
s3_prefix = "hello-cicd-sam"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
