AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-cicd-sam

  Sample SAM Template for hello-cicd-sam

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Handler: app.lambda_handler
    Environment:
      Variables:
        TABLE_NAME: MyTestTable

Resources:
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MyTestTable
      PrimaryKey:
        Name: ItemId
        Type: String

  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/index/
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get

  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/items/
      Policies:
      - DynamoDBReadPolicy:
          TableName: MyTestTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /items
            Method: get

  AddItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/add-item/
      Policies:
      - DynamoDBWritePolicy:
          TableName: MyTestTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /add-item
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
